; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25508.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\putu\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
